name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write # Required for GHCR push

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch: {} # Adds the manual "Run workflow" button

jobs:
  build:
    uses: crazy-max/.github/.github/workflows/bake-distribute-mp.yml@0acc187b016a2946786f201397bbcfb2c530ffc7
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            image: ghcr.io/tinymemoria/rtorrent-rutorrent
            login-registry: ghcr.io
            login-username: ${{ github.repository_owner }}
            login-secret-key: GITHUB_TOKEN
    with:
      target: image-all
      push: ${{ github.event_name != 'pull_request' }}
      cache: true
      cache-scope: build
      platforms: linux/arm/v7
      meta-image: ${{ matrix.image }}
      meta-tags: |
        type=match,pattern=(.*)-r,group=1
        type=ref,event=pr
        type=edge
      meta-labels: |
        org.opencontainers.image.title=rTorrent and ruTorrent
        org.opencontainers.image.description=rTorrent and ruTorrent
        org.opencontainers.image.vendor=tinymemoria
      login-registry: ${{ matrix.login-registry }}
      login-username: ${{ matrix.login-username }}
    secrets:
      login-password: ${{ secrets[matrix.login-secret-key] }}
