name: build-armv7

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch: # Adds "Run workflow" button

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (armv7)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/tinymemoria/rtorrent-rutorrent:latest
            ghcr.io/tinymemoria/rtorrent-rutorrent:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=rTorrent and ruTorrent
            org.opencontainers.image.description=rTorrent and ruTorrent
            org.opencontainers.image.vendor=tinymemoria
